name: mastodon_entities
description: Mastodon entities.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
