name: mastodon_entities
description: This package provides classes for working with Mastodon API entities in Dart.
version: 1.1.8
repository: https://github.com/MahanRahmati/mastodon-entities
topics:
  - mastodon
  - entities

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.3
  json_serializable: ^6.8.0
